# Generated by Django 3.2.5 on 2021-09-20 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('upc_code', models.CharField(max_length=20, null=True, unique=True)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=3, null=True)),
                ('zip', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('fax_number', models.CharField(max_length=20, null=True)),
                ('source', models.CharField(max_length=100, null=True)),
                ('products', models.ManyToManyField(to='inventory.Product')),
            ],
        ),
        migrations.CreateModel(
            name='SessionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('item_count', models.IntegerField()),
                ('closed', models.BooleanField()),
                ('report_file', models.FileField(null=True, upload_to='')),
                ('products', models.ManyToManyField(to='inventory.SessionItem')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('pack', models.IntegerField()),
                ('measure_unit', models.CharField(max_length=100)),
                ('box_number', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('creation_date', models.DateField(auto_now=True)),
                ('delivery_date', models.DateField()),
                ('po_number', models.IntegerField(primary_key=True, serialize=False)),
                ('number_ordered', models.IntegerField(null=True)),
                ('number_received', models.IntegerField(null=True)),
                ('products', models.ManyToManyField(to='inventory.PurchaseProduct')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.vendor')),
            ],
        ),
    ]
