# Generated by Django 3.2.5 on 2021-09-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210920_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseproduct',
            name='barcode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
