# Generated by Django 3.2.5 on 2021-09-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_purchaseproduct_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseproduct',
            name='received_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
