# Generated by Django 3.2.5 on 2021-09-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_purchaseproduct_received_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='badge',
            field=models.CharField(choices=[('S', 'success'), ('D', 'danger'), ('W', 'warning')], default='D', max_length=1),
        ),
    ]
